package com.javadeveloperzone.constant;

public class MailTemplate {
    public static final String LOGIN_REMAINDER_TEMPLATE="<!DOCTYPE html>"
            + "<html lang=\"en\">"
            + "<head>"
            + "    <meta charset=\"UTF-8\">"
            + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
            + "    <title>Attendance Reminder</title>"
            + "    <style>"
            + "        body {font-family: Arial, sans-serif; background-color: #f7f7f7; color: #333; margin: 0; padding: 0;}"
            + "        .container {width: 80%; margin: 0 auto; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);}"
            + "        .header {background-color: #007bff; color: #ffffff; padding: 10px; text-align: center; border-radius: 8px 8px 0 0;}"
            + "        .content {margin: 20px 0;}"
            + "        .footer {margin-top: 20px; text-align: center; font-size: 12px; color: #888;}"
            + "        .btn {display: inline-block; padding: 10px 20px; margin: 10px 0; color: #ffffff; background-color: #007bff; text-decoration: none; border-radius: 5px;}"
            + "    </style>"
            + "</head>"
            + "<body>"
            + "    <div class=\"container\">"
            + "        <div class=\"header\">"
            + "            <h1>Attendance Reminder</h1>"
            + "        </div>"
            + "        <div class=\"content\">"
            + "            <p>Our records indicate that you have not logged your attendance for today and you are not on approved leave. It is important to log your attendance to ensure accurate record-keeping.</p>"
            + "            <p>If you are experiencing issues with the attendance system, please contact the HR department immediately.</p>"
            + "            <p>Thank you for your cooperation.</p>"
            + "            <p>Best regards,</p>"
            + "            <p><strong>HR Department</strong></p>"
            + "        </div>"
            + "        <div class=\"footer\">"
            + "            <p>&copy; [ABHI] | This is an automated message, please do not reply.</p>"
            + "        </div>"
            + "    </div>"
            + "</body>"
            + "</html>";
}
